# Start from the official Python 3.7 container
FROM python:3.7.1

# Expose the default Quart port
EXPOSE 8000

# Set the main working directory
WORKDIR /home/avwx

# Set the service credentials as environment variables
ENV SECRET_KEY='MY_SECRET_KEY'
ENV DATABASE_URI='postgres://user:password==@url:port'

# Install the require Python packages
COPY requirements.txt /home/avwx/requirements.txt
RUN pip install -U pip
RUN pip install -Ur requirements.txt
RUN pip install -U gunicorn

# Copy the application code
COPY avwx_account /home/avwx/avwx_account
COPY gunicorn_config.py /home/avwx/gunicorn_config.py

# Run the application
CMD ["gunicorn", "avwx_account:app", "-c", "python:gunicorn_config.py"]