"""empty message

Revision ID: 26058f963139
Revises: c9f8674d3a2e
Create Date: 2019-09-06 23:44:50.966339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26058f963139'
down_revision = 'c9f8674d3a2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan', 'limit')
    # ### end Alembic commands ###
