"""empty message

Revision ID: 3d034abec611
Revises: a370ec804703
Create Date: 2018-12-28 01:08:49.885571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d034abec611'
down_revision = 'a370ec804703'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active_token', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('user', sa.Column('apitoken', sa.String(length=43), server_default='', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'apitoken')
    op.drop_column('user', 'active_token')
    # ### end Alembic commands ###
