"""empty message

Revision ID: 412199dfec5b
Revises: 76455d1ed0d3
Create Date: 2019-06-27 23:26:33.160674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '412199dfec5b'
down_revision = '76455d1ed0d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('user', sa.Column('updated', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated')
    op.drop_column('user', 'created')
    # ### end Alembic commands ###
