"""empty message

Revision ID: 76455d1ed0d3
Revises: 3d034abec611
Create Date: 2019-01-08 00:08:17.034145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76455d1ed0d3'
down_revision = '3d034abec611'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('customer_id', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('subscription_id', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('plan', sa.String(length=16), nullable=True))
    op.drop_column('user', 'company')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('company', sa.VARCHAR(length=100), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True))
    op.drop_column('user', 'subscription_id')
    op.drop_column('user', 'customer_id')
    op.drop_column('user', 'plan')
    # ### end Alembic commands ###
