"""empty message

Revision ID: a370ec804703
Revises: f33b5a4030a0
Create Date: 2018-12-26 11:46:49.807357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a370ec804703"
down_revision = "f33b5a4030a0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("role_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["role_id"], ["role.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_roles")
    # ### end Alembic commands ###
